name: SORACOM Orbit CI/CD

on:
  push:
   branches: [ master, staging]
  workflow_dispatch:

env:
  SORALET_ID: soralet-github-action-test
  SORALET_ID_STAGING: soralet-github-action-test-staging
  COVERAGE: jp

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: clone orbit-sdk-assemblyscript
        run: git clone https://github.com/soracom/orbit-sdk-assemblyscript.git ../orbit-sdk-assemblyscript
      - name: initialize
        run: npm run init
      - name: build
        run: npm run build
      - name: build optimized
        run: npm run build:optimized
      - name: test
        run: npm run test -- -u
      - name: upload assets
        uses: actions/upload-artifact@v2
        with:
          name: soracom-orbit
          path: build/soralet-optimized.wasm

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: soracom-orbit
      - name: Load secrets from 1password
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          AUTH_KEY_ID: op://Soracom/soracomApiKey/AUTH_KEY_ID
          AUTH_KEY: op://Soracom/soracomApiKey/AUTH_KEY
      - name: upload
        uses: kenichiro-kimura/action-soracom-upload-soralet@1.2.1
        id: upload
        with:
          soracom_auth_key: ${{ steps.op-load-secret.outputs.AUTH_KEY }}
          soracom_auth_key_id: ${{ steps.op-load-secret.outputs.AUTH_KEY_ID}}
          soracom_coverage: ${{ env.COVERAGE }}
          soracom_soralet_id: ${{ env.SORALET_ID }}
          soracom_soralet_filename: soralet-optimized.wasm
          soracom_delete_old_soralet: true
      - name: deploy staging
        uses: kenichiro-kimura/action-soracom-configure-orbit@1.1.1
        if: github.ref == 'refs/heads/staging'
        with:
          soracom_auth_key: ${{ secrets.AUTH_KEY }}
          soracom_auth_key_id: ${{ secrets.AUTH_KEY_ID}}
          soracom_coverage: ${{ env.COVERAGE }}
          soracom_soralet_code_srn: ${{ steps.upload.outputs.soralet_srn }}
          soracom_soralet_direction: uplink
          soracom_group_id: ${{ secrets.SORACOM_GROUP_ID_STG }}
          soracom_soralet_enabled: true
      - name: deploy production
        uses: kenichiro-kimura/action-soracom-configure-orbit@1.1.1
        if: github.ref == 'refs/heads/master'
        with:
          soracom_auth_key: ${{ secrets.AUTH_KEY }}
          soracom_auth_key_id: ${{ secrets.AUTH_KEY_ID}}
          soracom_coverage: ${{ env.COVERAGE }}
          soracom_soralet_code_srn: ${{ steps.upload.outputs.soralet_srn }}
          soracom_soralet_direction: uplink
          soracom_group_id: ${{ secrets.SORACOM_GROUP_ID_PROD }}
          soracom_soralet_enabled: true
