name: SORACOM Orbit CI/CD

on:
  push:
    branches: [ action-development ]
  workflow_dispatch:

env:
  SORALET_ID: soralet-github-action-test
  COVERAGE: jp

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kenichiro-kimura/orbit-assemblyscript:latest
      options: --cpus 1
      credentials:
        username: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
        password: ${{ secrets.GHCR_CONTAINER_REGISTRY_PASSWORD }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: initialize
        run: npm run init
      - name: copy libs
        run: cp -r /workspaces/orbit-sdk-assemblyscript ../
      - name: build
        run: npm run build
      - name: build optimized
        run: npm run build:optimized
      - name: test
        run: npm run test -- -u
      - name: upload assets
        uses: actions/upload-artifact@v2
        with:
          name: soracom-orbit
          path: build/soralet-optimized.wasm
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: soracom-orbit
      - name: deploy
        #uses: ./action/
        id: deploy
        uses: kenichiro-kimura/action-soracom-upload-soralet@1.2.0
        with:
          soracom_auth_key: ${{ secrets.AUTH_KEY }}
          soracom_auth_key_id: ${{ secrets.AUTH_KEY_ID}}
          soracom_coverage: ${{ env.COVERAGE }}
          soracom_soralet_id: ${{ env.SORALET_ID }}
          soracom_soralet_filename: soralet-optimized.wasm
          soracom_delete_old_soralet: true
      - name: update orbit configuration
        uses: kenichiro-kimura/action-soracom-simgroup-soralet@1.0.0
        with:
          soracom_auth_key: ${{ secrets.AUTH_KEY }}
          soracom_auth_key_id: ${{ secrets.AUTH_KEY_ID}}
          soracom_coverage: ${{ env.COVERAGE }}
          soracom_soralet_code_srn: ${{ steps.deploy.outputs.soralet_srn }}
          soracom_soralet_direction: uplink
          soracom_group_id: ${{ secrets.SORACOM_GROUP_ID }}

